from flask import Flask, render_template, request
import pickle
import numpy as np

with open('flight_delay.pkl', 'rb') as file:
    model = pickle.load(file) 
app = Flask(__name__)

@app.route("/",methods=['GET'])
def hello():
    return render_template('index.html')

@app.route("/predict", methods=['POST'])
def predict():
    if request.method == 'POST':

        d1 = request.form['Airline']
        # d1 = int(d1)
        # if (d1 == 'Commutair Aka Champlain Enterprises, Inc.'):
            # d1 = 7
        label_mapping = {
                        'Air Wisconsin Airlines Corp': 0,
                        'Alaska Airlines Inc.': 1,
                        'Allegiant Air': 2,
                        'American Airlines Inc.': 3,
                        'Cape Air': 4,
                        'Capital Cargo International': 5,
                        'Comair Inc.': 6,
                        'Commutair Aka Champlain Enterprises, Inc.': 7,
                        'Compass Airlines': 8,
                        'Delta Air Lines Inc.': 9,
                        'Empire Airlines Inc.': 10,
                        'Endeavor Air Inc.': 11,
                        'Envoy Air': 12,
                        'ExpressJet Airlines Inc.': 13,
                        'Frontier Airlines Inc.': 14,
                        'GoJet Airlines, LLC d/b/a United Express': 15,
                        'Hawaiian Airlines Inc.': 16,
                        'Horizon Air': 17,
                        'JetBlue Airways': 18,
                        'Mesa Airlines Inc.': 19,
                        'Peninsula Airways Inc.': 20,
                        'Republic Airlines': 21,
                        'SkyWest Airlines Inc.': 22,
                        'Southwest Airlines Co.': 23,
                        'Spirit Air Lines': 24,
                        'Trans States Airlines': 25,
                        'United Air Lines Inc.': 26,
                        'Virgin America': 27
                        }
        if d1 in label_mapping:
            d1 = label_mapping[d1]
    
        d2 = request.form['Origin']
        # d2 = int(d2)
        # if (d2=='GJT'):
        #     d2 = 144
        label_mapping = {
            'ABE': 0,
            'ABI': 1,
            'ABQ': 2,
            'ABR': 3,
            'ABY': 4,
            'ACK': 5,
            'ACT': 6,
            'ACV': 7,
            'ACY': 8,
            'ADK': 9,
            'ADQ': 10,
            'AEX': 11,
            'AGS': 12,
            'AKN': 13,
            'ALB': 14,
            'ALO': 15,
            'ALS': 16,
            'ALW': 17,
            'AMA': 18,
            'ANC': 19,
            'APN': 20,
            'ART': 21,
            'ASE': 22,
            'ATL': 23,
            'ATW': 24,
            'ATY': 25,
            'AUS': 26,
            'AVL': 27,
            'AVP': 28,
            'AZA': 29,
            'AZO': 30,
            'BDL': 31,
            'BET': 32,
            'BFF': 33,
            'BFL': 34,
            'BGM': 35,
            'BGR': 36,
            'BHM': 37,
            'BIH': 38,
            'BIL': 39,
            'BIS': 40,
            'BJI': 41,
            'BKG': 42,
            'BLI': 43,
            'BLV': 44,
            'BMI': 45,
            'BNA': 46,
            'BOI': 47,
            'BOS': 48,
            'BPT': 49,
            'BQK': 50,
            'BQN': 51,
            'BRD': 52,
            'BRO': 53,
            'BRW': 54,
            'BTM': 55,
            'BTR': 56,
            'BTV': 57,
            'BUF': 58,
            'BUR': 59,
            'BWI': 60,
            'BZN': 61,
            'CAE': 62,
            'CAK': 63,
            'CDB': 64,
            'CDC': 65,
            'CDV': 66,
            'CGI': 67,
            'CHA': 68,
            'CHO': 69,
            'CHS': 70,
            'CID': 71,
            'CIU': 72,
            'CKB': 73,
            'CLE': 74,
            'CLL': 75,
            'CLT': 76,
            'CMH': 77,
            'CMI': 78,
            'CMX': 79,
            'CNY': 80,
            'COD': 81,
            'COS': 82,
            'COU': 83,
            'CPR': 84,
            'CRP': 85,
            'CRW': 86,
            'CSG': 87,
            'CVG': 88,
            'CWA': 89,
            'CYS': 90,
            'DAB': 91,
            'DAL': 92,
            'DAY': 93,
            'DBQ': 94,
            'DCA': 95,
            'DDC': 96,
            'DEC': 97,
            'DEN': 98,
            'DFW': 99,
            'DHN': 100,
            'DIK': 101,
            'DLG': 102,
            'DLH': 103,
            'DRO': 104,
            'DRT': 105,
            'DSM': 106,
            'DTW': 107,
            'DUT': 108,
            'DVL': 109,
            'EAR': 110,
            'EAT': 111,
            'EAU': 112,
            'ECP': 113,
            'EGE': 114,
            'EKO': 115,
            'ELM': 116,
            'ELP': 117,
            'ERI': 118,
            'ESC': 119,
            'EUG': 120,
            'EVV': 121,
            'EWN': 122,
            'EWR': 123,
            'EYW': 124,
            'FAI': 125,
            'FAR': 126,
            'FAT': 127,
            'FAY': 128,
            'FCA': 129,
            'FLG': 130,
            'FLL': 131,
            'FLO': 132,
            'FNT': 133,
            'FOD': 134,
            'FSD': 135,
            'FSM': 136,
            'FWA': 137,
            'GCC': 138,
            'GCK': 139,
            'GEG': 140,
            'GFK': 141,
            'GGG': 142,
            'GJT': 143,
            'GNV': 144,
            'GPT': 145,
            'GRB': 146,
            'GRI': 147,
            'GRK': 148,
            'GRR': 149,
            'GSO': 150,
            'GSP': 151,
            'GST': 152,
            'GTF': 153,
            'GTR': 154,
            'GUC': 155,
            'GUM': 156,
            'HDN': 157,
            'HGR': 158,
            'HHH': 159,
            'HIB': 160,
            'HLN': 161,
            'HNL': 162,
            'HOB': 163,
            'HOU': 164,
            'HPN': 165,
            'HRL': 166,
            'HSV': 167,
            'HTS': 168,
            'HVN': 169,
            'HYA': 170,
            'HYS': 171,
            'IAD': 172,
            'IAG': 173,
            'IAH': 174,
            'ICT': 175,
            'IDA': 176,
            'ILG': 177,
            'ILM': 178,
            'IMT': 179,
            'IND': 180,
            'INL': 181,
            'IPT': 182,
            'ISN': 183,
            'ISP': 184,
            'ITH': 185,
            'ITO': 186,
            'JAC': 187,
            'JAN': 188,
            'JAX': 189,
            'JFK': 190,
            'JHM': 191,
            'JLN': 192,
            'JMS': 193,
            'JNU': 194,
            'JST': 195,
            'KOA': 196,
            'KTN': 197,
            'LAN': 198,
            'LAR': 199,
            'LAS': 200,
            'LAW': 201,
            'LAX': 202,
            'LBB': 203,
            'LBE': 204,
            'LBF': 205,
            'LBL': 206,
            'LCH': 207,
            'LCK': 208,
            'LEX': 209,
            'LFT': 210,
            'LGA': 211,
            'LGB': 212,
            'LIH': 213,
            'LIT': 214,
            'LNK': 215,
            'LNY': 216,
            'LRD': 217,
            'LSE': 218,
            'LWB': 219,
            'LWS': 220,
            'LYH': 221,
            'MAF': 222,
            'MBS': 223,
            'MCI': 224,
            'MCO': 225,
            'MCW': 226,
            'MDT': 227,
            'MDW': 228,
            'MEI': 229,
            'MEM': 230,
            'MFE': 231,
            'MFR': 232,
            'MGM': 233,
            'MHK': 234,
            'MHT': 235,
            'MIA': 236,
            'MKE': 237,
            'MKG': 238,
            'MKK': 239,
            'MLB': 240,
            'MLI': 241,
            'MLU': 242,
            'MMH': 243,
            'MOB': 244,
            'MOT': 245,
            'MQT': 246,
            'MRY': 247,
            'MSN': 248,
            'MSO': 249,
            'MSP': 250,
            'MSY': 251,
            'MTJ': 252,
            'MVY': 253,
            'MYR': 254,
            'OAJ': 255,
            'OAK': 256,
            'OGD': 257,
            'OGG': 258,
            'OGS': 259,
            'OKC': 260,
            'OMA': 261,
            'OME': 262,
            'ONT': 263,
            'ORD': 264,
            'ORF': 265,
            'ORH': 266,
            'OTH': 267,
            'OTZ': 268,
            'OWB': 269,
            'PAE': 270,
            'PAH': 271,
            'PBG': 272,
            'PBI': 273,
            'PDX': 274,
            'PGD': 275,
            'PGV': 276,
            'PHF': 277,
            'PHL': 278,
            'PHX': 279,
            'PIA': 280,
            'PIB': 281,
            'PIE': 282,
            'PIH': 283,
            'PIR': 284,
            'PIT': 285,
            'PLN': 286,
            'PNS': 287,
            'PPG': 288,
            'PQI': 289,
            'PRC': 290,
            'PSC': 291,
            'PSE': 292,
            'PSG': 293,
            'PSM': 294,
            'PSP': 295,
            'PUB': 296,
            'PUW': 297,
            'PVD': 298,
            'PVU': 299,
            'PWM': 300,
            'RAP': 301,
            'RDD': 302,
            'RDM': 303,
            'RDU': 304,
            'RFD': 305,
            'RHI': 306,
            'RIC': 307,
            'RIW': 308,
            'RKS': 309,
            'RNO': 310,
            'ROA': 311,
            'ROC': 312,
            'ROP': 313,
            'ROW': 314,
            'RST': 315,
            'RSW': 316,
            'SAF': 317,
            'SAN': 318,
            'SAT': 319,
            'SAV': 320,
            'SBA': 321,
            'SBN': 322,
            'SBP': 323,
            'SBY': 324,
            'SCC': 325,
            'SCE': 326,
            'SCK': 327,
            'SDF': 328,
            'SEA': 329,
            'SFB': 330,
            'SFO': 331,
            'SGF': 332,
            'SGU': 333,
            'SHD': 334,
            'SHR': 335,
            'SHV': 336,
            'SIT': 337,
            'SJC': 338,
            'SJT': 339,
            'SJU': 340,
            'SLC': 341,
            'SLN': 342,
            'SMF': 343,
            'SMX': 344,
            'SNA': 345,
            'SPI': 346,
            'SPN': 347,
            'SPS': 348,
            'SRQ': 349,
            'STC': 350,
            'STL': 351,
            'STS': 352,
            'STT': 353,
            'STX': 354,
            'SUN': 355,
            'SUX': 356,
            'SWF': 357,
            'SWO': 358,
            'SYR': 359,
            'TBN': 360,
            'TLH': 361,
            'TOL': 362,
            'TPA': 363,
            'TRI': 364,
            'TTN': 365,
            'TUL': 366,
            'TUS': 367,
            'TVC': 368,
            'TWF': 369,
            'TXK': 370,
            'TYR': 371,
            'TYS': 372,
            'UIN': 373,
            'USA': 374,
            'VCT': 375,
            'VEL': 376,
            'VLD': 377,
            'VPS': 378,
            'WRG': 379,
            'WYS': 380,
            'XNA': 381,
            'XWA': 382,
            'YAK': 383,
            'YKM': 384,
            'YUM': 385
        }

        if d2 in label_mapping:
            d2 = label_mapping[d2]


        d3 = request.form['Destination']
        # d3 = int(d3)
        # if(d3=='DEN'):
        #     d3 = 98

        if d3 in label_mapping:
            d3 = label_mapping[d3]

        d4 = request.form['Departure_Time']
        d4 = int(d4)

        d5 = request.form['Origin_City']
        # d5 = int(d5)
        # if(d5 == 'Grand Junction, CO'):
        #     d5 = 129
        label_mapping = {   
                            'Aberdeen, SD': 0,
                            'Abilene, TX': 1,
                            'Adak Island, AK': 2,
                            'Aguadilla, PR': 3,
                            'Akron, OH': 4,
                            'Alamosa, CO': 5,
                            'Albany, GA': 6,
                            'Albany, NY': 7,
                            'Albuquerque, NM': 8,
                            'Alexandria, LA': 9,
                            'Allentown/Bethlehem/Easton, PA': 10,
                            'Alpena, MI': 11,
                            'Amarillo, TX': 12,
                            'Anchorage, AK': 13,
                            'Appleton, WI': 14,
                            'Arcata/Eureka, CA': 15,
                            'Asheville, NC': 16,
                            'Ashland, WV': 17,
                            'Aspen, CO': 18,
                            'Atlanta, GA': 19,
                            'Atlantic City, NJ': 20,
                            'Augusta, GA': 21,
                            'Austin, TX': 22,
                            'Bakersfield, CA': 23,
                            'Baltimore, MD': 24,
                            'Bangor, ME': 25,
                            'Barrow, AK': 26,
                            'Baton Rouge, LA': 27,
                            'Beaumont/Port Arthur, TX': 28,
                            'Belleville, IL': 29,
                            'Bellingham, WA': 30,
                            'Bemidji, MN': 31,
                            'Bend/Redmond, OR': 32,
                            'Bethel, AK': 33,
                            'Billings, MT': 34,
                            'Binghamton, NY': 35,
                            'Birmingham, AL': 36,
                            'Bishop, CA': 37,
                            'Bismarck/Mandan, ND': 38,
                            'Bloomington/Normal, IL': 39,
                            'Boise, ID': 40,
                            'Boston, MA': 41,
                            'Bozeman, MT': 42,
                            'Brainerd, MN': 43,
                            'Branson, MO': 44,
                            'Bristol/Johnson City/Kingsport, TN': 45,
                            'Brownsville, TX': 46,
                            'Brunswick, GA': 47,
                            'Buffalo, NY': 48,
                            'Burbank, CA': 49,
                            'Burlington, VT': 50,
                            'Butte, MT': 51,
                            'CONCORD, NC': 52,
                            'Cape Girardeau, MO': 53,
                            'Casper, WY': 54,
                            'Cedar City, UT': 55,
                            'Cedar Rapids/Iowa City, IA': 56,
                            'Champaign/Urbana, IL': 57,
                            'Charleston, SC': 58,
                            'Charleston/Dunbar, WV': 59,
                            'Charlotte Amalie, VI': 60,
                            'Charlotte, NC': 61,
                            'Charlottesville, VA': 62,
                            'Chattanooga, TN': 63,
                            'Cheyenne, WY': 64,
                            'Chicago, IL': 65,
                            'Christiansted, VI': 66,
                            'Cincinnati, OH': 67,
                            'Clarksburg/Fairmont, WV': 68,
                            'Cleveland, OH': 69,
                            'Cody, WY': 70,
                            'Cold Bay, AK': 71,
                            'College Station/Bryan, TX': 72,
                            'Colorado Springs, CO': 73,
                            'Columbia, MO': 74,
                            'Columbia, SC': 75,
                            'Columbus, GA': 76,
                            'Columbus, MS': 77,
                            'Columbus, OH': 78,
                            'Concord, NC': 79,
                            'Cordova, AK': 80,
                            'Corpus Christi, TX': 81,
                            'Dallas, TX': 82,
                            'Dallas/Fort Worth, TX': 83,
                            'Dayton, OH': 84,
                            'Daytona Beach, FL': 85,
                            'Deadhorse, AK': 86,
                            'Decatur, IL': 87,
                            'Del Rio, TX': 88,
                            'Denver, CO': 89,
                            'Des Moines, IA': 90,
                            'Detroit, MI': 91,
                            'Devils Lake, ND': 92,
                            'Dickinson, ND': 93,
                            'Dillingham, AK': 94,
                            'Dodge City, KS': 95,
                            'Dothan, AL': 96,
                            'Dubuque, IA': 97,
                            'Duluth, MN': 98,
                            'Durango, CO': 99,
                            'Eagle, CO': 100,
                            'Eau Claire, WI': 101,
                            'El Paso, TX': 102,
                            'Elko, NV': 103,
                            'Elmira/Corning, NY': 104,
                            'Erie, PA': 105,
                            'Escanaba, MI': 106,
                            'Eugene, OR': 107,
                            'Evansville, IN': 108,
                            'Everett, WA': 109,
                            'Fairbanks, AK': 110,
                            'Fargo, ND': 111,
                            'Fayetteville, AR': 112,
                            'Fayetteville, NC': 113,
                            'Flagstaff, AZ': 114,
                            'Flint, MI': 115,
                            'Florence, SC': 116,
                            'Fort Dodge, IA': 117,
                            'Fort Lauderdale, FL': 118,
                            'Fort Leonard Wood, MO': 119,
                            'Fort Myers, FL': 120,
                            'Fort Smith, AR': 121,
                            'Fort Wayne, IN': 122,
                            'Fresno, CA': 123,
                            'Gainesville, FL': 124,
                            'Garden City, KS': 125,
                            'Gillette, WY': 126,
                            'Grand Forks, ND': 127,
                            'Grand Island, NE': 128,
                            'Grand Junction, CO': 129,
                            'Grand Rapids, MI': 130,
                            'Great Falls, MT': 131,
                            'Green Bay, WI': 132,
                            'Greensboro/High Point, NC': 133,
                            'Greenville, NC': 134,
                            'Greer, SC': 135,
                            'Guam, TT': 136,
                            'Gulfport/Biloxi, MS': 137,
                            'Gunnison, CO': 138,
                            'Gustavus, AK': 139,
                            'Hagerstown, MD': 140,
                            'Hancock/Houghton, MI': 141,
                            'Harlingen/San Benito, TX': 142,
                            'Harrisburg, PA': 143,
                            'Hartford, CT': 144,
                            'Hattiesburg/Laurel, MS': 145,
                            'Hayden, CO': 146,
                            'Hays, KS': 147,
                            'Helena, MT': 148,
                            'Hibbing, MN': 149,
                            'Hilo, HI': 150,
                            'Hilton Head, SC': 151,
                            'Hobbs, NM': 152,
                            'Honolulu, HI': 153,
                            'Hoolehua, HI': 154,
                            'Houston, TX': 155,
                            'Huntsville, AL': 156,
                            'Hyannis, MA': 157,
                            'Idaho Falls, ID': 158,
                            'Indianapolis, IN': 159,
                            'International Falls, MN': 160,
                            'Iron Mountain/Kingsfd, MI': 161,
                            'Islip, NY': 162,
                            'Ithaca/Cortland, NY': 163,
                            'Jackson, WY': 164,
                            'Jackson/Vicksburg, MS': 165,
                            'Jacksonville, FL': 166,
                            'Jacksonville/Camp Lejeune, NC': 167,
                            'Jamestown, ND': 168,
                            'Johnstown, PA': 169,
                            'Joplin, MO': 170,
                            'Juneau, AK': 171,
                            'Kahului, HI': 172,
                            'Kalamazoo, MI': 173,
                            'Kalispell, MT': 174,
                            'Kansas City, MO': 175,
                            'Kapalua, HI': 176,
                            'Kearney, NE': 177,
                            'Ketchikan, AK': 178,
                            'Key West, FL': 179,
                            'Killeen, TX': 180,
                            'King Salmon, AK': 181,
                            'Knoxville, TN': 182,
                            'Kodiak, AK': 183,
                            'Kona, HI': 184,
                            'Kotzebue, AK': 185,
                            'La Crosse, WI': 186,
                            'Lafayette, LA': 187,
                            'Lake Charles, LA': 188,
                            'Lanai, HI': 189,
                            'Lansing, MI': 190,
                            'Laramie, WY': 191,
                            'Laredo, TX': 192,
                            'Las Vegas, NV': 193,
                            'Latrobe, PA': 194,
                            'Lawton/Fort Sill, OK': 195,
                            'Lewisburg, WV': 196,
                            'Lewiston, ID': 197,
                            'Lexington, KY': 198,
                            'Liberal, KS': 199,
                            'Lihue, HI': 200,
                            'Lincoln, NE': 201,
                            'Little Rock, AR': 202,
                            'Long Beach, CA': 203,
                            'Longview, TX': 204,
                            'Los Angeles, CA': 205,
                            'Louisville, KY': 206,
                            'Lubbock, TX': 207,
                            'Lynchburg, VA': 208,
                            'Madison, WI': 209,
                            'Mammoth Lakes, CA': 210,
                            'Manchester, NH': 211,
                            'Manhattan/Ft. Riley, KS': 212,
                            'Marquette, MI': 213,
                            "Martha's Vineyard, MA": 214,
                            'Mason City, IA': 215,
                            'Medford, OR': 216,
                            'Melbourne, FL': 217,
                            'Memphis, TN': 218,
                            'Meridian, MS': 219,
                            'Miami, FL': 220,
                            'Midland/Odessa, TX': 221,
                            'Milwaukee, WI': 222,
                            'Minneapolis, MN': 223,
                            'Minot, ND': 224,
                            'Mission/McAllen/Edinburg, TX': 225,
                            'Missoula, MT': 226,
                            'Moab, UT': 227,
                            'Mobile, AL': 228,
                            'Moline, IL': 229,
                            'Monroe, LA': 230,
                            'Monterey, CA': 231,
                            'Montgomery, AL': 232,
                            'Montrose/Delta, CO': 233,
                            'Mosinee, WI': 234,
                            'Muskegon, MI': 235,
                            'Myrtle Beach, SC': 236,
                            'Nantucket, MA': 237,
                            'Nashville, TN': 238,
                            'New Bern/Morehead/Beaufort, NC': 239,
                            'New Haven, CT': 240,
                            'New Orleans, LA': 241,
                            'New York, NY': 242,
                            'Newark, NJ': 243,
                            'Newburgh/Poughkeepsie, NY': 244,
                            'Newport News/Williamsburg, VA': 245,
                            'Niagara Falls, NY': 246,
                            'Nome, AK': 247,
                            'Norfolk, VA': 248,
                            'North Bend/Coos Bay, OR': 249,
                            'North Platte, NE': 250,
                            'Oakland, CA': 251,
                            'Ogden, UT': 252,
                            'Ogdensburg, NY': 253,
                            'Oklahoma City, OK': 254,
                            'Omaha, NE': 255,
                            'Ontario, CA': 256,
                            'Orlando, FL': 257,
                            'Owensboro, KY': 258,
                            'Paducah, KY': 259,
                            'Pago Pago, TT': 260,
                            'Palm Springs, CA': 261,
                            'Panama City, FL': 262,
                            'Pasco/Kennewick/Richland, WA': 263,
                            'Pellston, MI': 264,
                            'Pensacola, FL': 265,
                            'Peoria, IL': 266,
                            'Petersburg, AK': 267,
                            'Philadelphia, PA': 268,
                            'Phoenix, AZ': 269,
                            'Pierre, SD': 270,
                            'Pittsburgh, PA': 271,
                            'Plattsburgh, NY': 272,
                            'Pocatello, ID': 273,
                            'Ponce, PR': 274,
                            'Portland, ME': 275,
                            'Portland, OR': 276,
                            'Portsmouth, NH': 277,
                            'Prescott, AZ': 278,
                            'Presque Isle/Houlton, ME': 279,
                            'Providence, RI': 280,
                            'Provo, UT': 281,
                            'Pueblo, CO': 282,
                            'Pullman, WA': 283,
                            'Punta Gorda, FL': 284,
                            'Quincy, IL': 285,
                            'Raleigh/Durham, NC': 286,
                            'Rapid City, SD': 287,
                            'Redding, CA': 288,
                            'Reno, NV': 289,
                            'Rhinelander, WI': 290,
                            'Richmond, VA': 291,
                            'Riverton/Lander, WY': 292,
                            'Roanoke, VA': 293,
                            'Rochester, MN': 294,
                            'Rochester, NY': 295,
                            'Rock Springs, WY': 296,
                            'Rockford, IL': 297,
                            'Roswell, NM': 298,
                            'Rota, TT': 299,
                            'Sacramento, CA': 300,
                            'Saginaw/Bay City/Midland, MI': 301,
                            'Saipan, TT': 302,
                            'Salina, KS': 303,
                            'Salisbury, MD': 304,
                            'Salt Lake City, UT': 305,
                            'San Angelo, TX': 306,
                            'San Antonio, TX': 307,
                            'San Diego, CA': 308,
                            'San Francisco, CA': 309,
                            'San Jose, CA': 310,
                            'San Juan, PR': 311,
                            'San Luis Obispo, CA': 312,
                            'Sanford, FL': 313,
                            'Santa Ana, CA': 314,
                            'Santa Barbara, CA': 315,
                            'Santa Fe, NM': 316,
                            'Santa Maria, CA': 317,
                            'Santa Rosa, CA': 318,
                            'Sarasota/Bradenton, FL': 319,
                            'Sault Ste. Marie, MI': 320,
                            'Savannah, GA': 321,
                            'Scottsbluff, NE': 322,
                            'Scranton/Wilkes-Barre, PA': 323,
                            'Seattle, WA': 324,
                            'Sheridan, WY': 325,
                            'Shreveport, LA': 326,
                            'Sioux City, IA': 327,
                            'Sioux Falls, SD': 328,
                            'Sitka, AK': 329,
                            'South Bend, IN': 330,
                            'Spokane, WA': 331,
                            'Springfield, IL': 332,
                            'Springfield, MO': 333,
                            'St. Cloud, MN': 334,
                            'St. George, UT': 335,
                            'St. Louis, MO': 336,
                            'St. Petersburg, FL': 337,
                            'State College, PA': 338,
                            'Staunton, VA': 339,
                            'Stillwater, OK': 340,
                            'Stockton, CA': 341,
                            'Sun Valley/Hailey/Ketchum, ID': 342,
                            'Syracuse, NY': 343,
                            'Tallahassee, FL': 344,
                            'Tampa, FL': 345,
                            'Texarkana, AR': 346,
                            'Toledo, OH': 347,
                            'Traverse City, MI': 348,
                            'Trenton, NJ': 349,
                            'Tucson, AZ': 350,
                            'Tulsa, OK': 351,
                            'Twin Falls, ID': 352,
                            'Tyler, TX': 353,
                            'Unalaska, AK': 354,
                            'Valdosta, GA': 355,
                            'Valparaiso, FL': 356,
                            'Vernal, UT': 357,
                            'Victoria, TX': 358,
                            'Waco, TX': 359,
                            'Walla Walla, WA': 360,
                            'Washington, DC': 361,
                            'Waterloo, IA': 362,
                            'Watertown, NY': 363,
                            'Watertown, SD': 364,
                            'Wenatchee, WA': 365,
                            'West Palm Beach/Palm Beach, FL': 366,
                            'West Yellowstone, MT': 367,
                            'White Plains, NY': 368,
                            'Wichita Falls, TX': 369,
                            'Wichita, KS': 370,
                            'Williamsport, PA': 371,
                            'Williston, ND': 372,
                            'Wilmington, DE': 373,
                            'Wilmington, NC': 374,
                            'Worcester, MA': 375,
                            'Wrangell, AK': 376,
                            'Yakima, WA': 377,
                            'Yakutat, AK': 378,
                            'Yuma, AZ': 379
                        }
        if d5 in label_mapping:
            d5 = label_mapping[d5]

        d6 = request.form['Origin_State']
        # d6 = int(d6)
        # if(d6 == 'Colorado'):
        #     d6 = 5

        label_mapping1 = {
                            'Alabama': 0,
                            'Alaska': 1,
                            'Arizona': 2,
                            'Arkansas': 3,
                            'California': 4,
                            'Colorado': 5,
                            'Connecticut': 6,
                            'Delaware': 7,
                            'Florida': 8,
                            'Georgia': 9,
                            'Hawaii': 10,
                            'Idaho': 11,
                            'Illinois': 12,
                            'Indiana': 13,
                            'Iowa': 14,
                            'Kansas': 15,
                            'Kentucky': 16,
                            'Louisiana': 17,
                            'Maine': 18,
                            'Maryland': 19,
                            'Massachusetts': 20,
                            'Michigan': 21,
                            'Minnesota': 22,
                            'Mississippi': 23,
                            'Missouri': 24,
                            'Montana': 25,
                            'Nebraska': 26,
                            'Nevada': 27,
                            'New Hampshire': 28,
                            'New Jersey': 29,
                            'New Mexico': 30,
                            'New York': 31,
                            'North Carolina': 32,
                            'North Dakota': 33,
                            'Ohio': 34,
                            'Oklahoma': 35,
                            'Oregon': 36,
                            'Pennsylvania': 37,
                            'Puerto Rico': 38,
                            'Rhode Island': 39,
                            'South Carolina': 40,
                            'South Dakota': 41,
                            'Tennessee': 42,
                            'Texas': 43,
                            'U.S. Pacific Trust Territories and Possessions': 44,
                            'U.S. Virgin Islands': 45,
                            'Utah': 46,
                            'Vermont': 47,
                            'Virginia': 48,
                            'Washington': 49,
                            'West Virginia': 50,
                            'Wisconsin': 51,
                            'Wyoming': 52  
                        }
        if d6 in label_mapping1:
            d6 = label_mapping1[d6]
            d6 = int(d6)

        d7 = request.form['Destination_City']
        # d7 = int(d7)
        # if (d7 == 'Denver, CO'):
        #     d7 = 89
        if d7 in label_mapping:
            d7 = label_mapping[d7]

        d8 = request.form['Destination_State']
        # d8 = int(d8)
        # if(d8 == 'Colorado'):
        #     d8 = 5
        if d8 in label_mapping1:
            d8 = label_mapping1[d8]
            d8 = int(d8)
            
        d9 = request.form['Arrival_Time']
        d9 = int(d9)

        # d10 = request.form['Year']
        d10 = np.random.choice([2018,2019,2021,2022])

        # d11 = request.form['Month']
        d11 = np.random.randint(1,13)

        #arr = np.array([[d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11]])
        pred = model.predict(np.array([[d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11]]))[0]
        if pred == 0:
            return render_template('index.html', prediction_text="delay anywhere from 15 to 60 mins")
        else:
            return render_template('index.html', prediction_text="maximum delay of 15 mins")
    else:
        return render_template('index.html')

app.run(debug=True) 
